services:
  boot_postgres:
    container_name: boot_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env

  redis-cache:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass "Password@123"